### ISSUE TITLE
Saving searched files as .json instead of .txt in data/dump/own/<file>

### ISSUE THREAD

**Issue by sudheesh001** [Orbiter/loklak#8] opened 2015-03-24 06:29 UTC
The files are currently being saved as .txt, wouldn't it be a better option to convert them to .json ? Is there something related to the space that it takes up on the system ?

**Comment by Orbiter** [comment] 2015-03-24 08:11
The file is constantly written whenever a new message is added. To convert it to json it would at least need an open bracket at the file start while the closing bracket at the file end would constantly needed to be replaced by new json output.
This works as intended, the dump file was not supposed to be json, there is no need for it to be json and it is not named .json on purpose.

**Closed by Orbiter** 2015-03-24 08:11 UTC

**Comment by sudheesh001** [comment] 2015-03-24 09:00
Agreed :+1:
